---

- name: create ssh keys
  command: ssh-keygen -t rsa -b 2048 -f /home/vagrant/.ssh/id_rsa -q -N ""
  args:
    creates: "/home/vagrant/.ssh/id_rsa"
  sudo: no
- name: copy authorized_keys
  command: cp /home/vagrant/.ssh/id_rsa.pub authorized_keys
  sudo: no
